### ISSUE TITLE
Running customvis start or customvis pack on the Sankey code sample errors out 'Failed to start the bundle' and 'Failed to pack the bundle.'

### ISSUE THREAD

**Issue by brnnnfx** [IBM/ca_customvis#5]
**What is the issue?**

Cannot successfully run customvis start or customvis pack on the Sankey code sample

I have cloned this repository, but the only visualization type I cannot use is the Sankey -> https://github.com/IBM/ca_customvis/tree/master/code-samples/11.1.x/sankey

**What specifically happens?**

I get the following response when running `customvis start`

> [Info] [3:26:21 PM] Generating vizdef.xml
> [Error] [3:26:21 PM] Failed to start the bundle.
> [Error] [3:26:21 PM] Could not find dependency "@businessanalytics/customvis-lib". Please check your package.json if "@businessanalytics/customvis-lib" is defined as a dependency.

And yes, `@businessanalytics/customvis-lib` is defined as a dependency in the package.json

I get the following response when running `customvis pack`

> [Info] [3:30:01 PM] Start packing....
> rpt2: options error TS2688 Cannot find type definition file for 'd3'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-array'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-axis'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-brush'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-chord'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-collection'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-color'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-contour'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-dispatch'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-drag'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-dsv'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-ease'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-fetch'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-force'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-format'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-geo'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-hierarchy'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-interpolate'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-path'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-polygon'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-quadtree'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-random'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-scale'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-scale-chromatic'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-selection'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-shape'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-time'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-time-format'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-timer'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-transition'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-voronoi'.
> rpt2: options error TS2688 Cannot find type definition file for 'd3-zoom'.
> rpt2: options error TS2688 Cannot find type definition file for 'geojson'.
> rpt2: options error TS2688 Cannot find type definition file for 'promise-polyfill'.
> rpt2: options error TS2688 Cannot find type definition file for 'requirejs'.
> [Info] [3:30:01 PM] Generating vizdef.xml
> [Error] [3:30:01 PM] Failed to pack the bundle.
> [Error] [3:30:01 PM] Could not find dependency "@businessanalytics/customvis-lib". Please check your package.json if "@businessanalytics/customvis-lib" is defined as a dependency.

**Other details**

Running macOS 10.15.3, using zsh
node.js version 12.14.1
npm version 6.13.7

**Comment by tsteijvers** [comment]
What is the version of customvis that you are using (type `customvis --version`)?
I was not able to reproduce, could you send me a zip of the contents of your Sankey folder?
After you have zipped Sankey, can you try to do a `customvis clean` followed by another `customvis start`? Maybe a corrupt package-lock.json causes the issue.

**Comment by brnnnfx** [comment]
Hi @tsteijvers `customvis clean` worked, thank you!

I am using customvis version 1.1.118. I have attached a copy of the Sankey folder that I had cloned from this repo if you wish to review it.

[sankey.zip](https://github.com/IBM/ca_customvis/files/4225394/sankey.zip)

**Comment by tsteijvers** [comment]
Hi @brnnnfx, looks like your node_modules folder got messed up... Using `customvis clean` gave you a fresh, working copy. Glad it works now!
